### ISSUE TITLE
reCaptcha solver Bugs vers 0.30b1

### ISSUE THREAD

**Issue by Pocker88** [Wikidepia/hektCaptcha-extension#37]
Sir @Wikidepia I Found some bugs in the extension: 1) very fast clicking on picture elements captcha. 2) after selecting a certain element by clicking on it, the script clicks on it again after a short time and thus removes the "selection" MOTO/traffic LIGHT. 3) reloading/refreshing the captcha page is very fast despite the 3200 ms setting.

**Comment by Wikidepia** [comment]
Thanks, I will check it later

**Comment by Pocker88** [comment]
> after 8 times reload CAPTCHA 

![Screenshot_2023-05-09-11-14-40-41_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/79075067/237036633-fd9cbaee-783c-48bd-b153-343b781835de.jpg)

**Comment by Wikidepia** [comment]
> hello support for this challenge ![2222](https://user-images.githubusercontent.com/54672741/237502475-1064d6cf-722e-4f25-8972-e6edd558be51.png)

I dont have enough data for that yet. Also please open new issue, dont hijack existing issue.

**Comment by Pocker88** [comment]
> > hello support for this challenge ![2222](https://user-images.githubusercontent.com/54672741/237502475-1064d6cf-722e-4f25-8972-e6edd558be51.png)
> 
> I dont have enough data for that yet. Also please open new issue, dont hijack existing issue.

![Screenshot_2023-05-17-09-50-57-15_4d38fce200f96aeac5e860e739312e76](https://github.com/Wikidepia/hektCaptcha-extension/assets/79075067/559a9e19-386f-4b30-991c-1cd9f66d3c43)
On some pages , extension didn't see ReCaptcha.. and not solve (((

**Comment by cryptomaniac123** [comment]
It's not working on opera gx and brave.

**Comment by Serega007RU** [comment]
> It's not working on opera gx and brave.

For Opera, you need to allow access to the captcha, for this you need to check the box next to "Allow access to search result" on the extensions page.
About Brave, I do not know

**Comment by cryptomaniac123** [comment]
> > It's not working on opera gx and brave.
> 
> For Opera, you need to allow access to the captcha, for this you need to check the box next to "Allow access to search result" on the extensions page. About Brave, I do not know

thank you now is opening the recaptcha. but still have a problem, its not solving the the captchas, just skipping pages. i enter in a page with captcha then begin in the audio capctha and i manually change for the image ones (because its not changing automatcaly), after that its just skiping page after page. srry about my english, its not my first language.

**Comment by Serega007RU** [comment]
Most likely you have a problem with the captcha language, you probably have a captcha displayed not in English, and the extension can solve the captcha only in English. A correction has already been made in this commit https://github.com/Wikidepia/hektCaptcha-extension/commit/8b19b7b44d0597d1f50763f7f38e01c77553b81d but the author should release a new release so that you can download a new version of the extension with this fix

**Comment by Pocker88** [comment]
> It's not working on opera gx and brave.

![Screenshot_2023-05-21-10-55-23-97_4d38fce200f96aeac5e860e739312e76](https://github.com/Wikidepia/hektCaptcha-extension/assets/79075067/68906399-336e-47d2-9143-b65b09424f0f)

simply read this on instructions..

**Comment by Serega007RU** [comment]
The problem is that the author makes and writes the code for himself and not for public access. There was already a problem #40, the author helped solve it, but the project is still not fully built, for some reason there are no ort models to solve reCAPTCHA, why they are not included in build I do not know. Therefore, the CLI will not help here

**Comment by cryptomaniac123** [comment]
> Most likely you have a problem with the captcha language, you probably have a captcha displayed not in English, and the extension can solve the captcha only in English. A correction has already been made in this commit [8b19b7b](https://github.com/Wikidepia/hektCaptcha-extension/commit/8b19b7b44d0597d1f50763f7f38e01c77553b81d) but the author should release a new release so that you can download a new version of the extension with this fix

That was exactly the problem friend, thank you for the help> I have change my browser language and everything its working fine now.
