### ISSUE TITLE
Recaptcha solver not working in some sites

### ISSUE THREAD

**Issue by ahmedok2022** [Wikidepia/hektCaptcha-extension#45]
Recaptcha solver not working in some sites like:
https://illink.net/Yd4121

**Comment by Serega007RU** [comment]
Your link is not working

**Comment by ahmedok2022** [comment]
try this
https://go.techgeek.digital/u21bk

**Comment by ahmedok2022** [comment]
> 

sorry for that but I mean  the recapcha in the this shortlink

**Comment by ahmedok2022** [comment]
works fine.
thank you

**Comment by Rusenche** [comment]
Recaptcha solver not working - https://up-load.io/1bv6wr29l23y

**Comment by Wikidepia** [comment]
> Recaptcha solver not working - https://up-load.io/1bv6wr29l23y

Cannot see the file, please upload elsewhere

**Comment by Rusenche** [comment]
How can you not see the obvious?!

![SJah](https://github.com/Wikidepia/hektCaptcha-extension/assets/18578128/31ba5951-23e7-4566-88ad-39abe25eee0c)

**Comment by Serega007RU** [comment]
are you talking about reCAPTCHA on this page? HektCaptcha can pass it, are you using the latest version? What version of hektCaptcha do you have?

**Comment by Wikidepia** [comment]
> How can you not see the obvious?!
> 
> ![SJah](https://user-images.githubusercontent.com/18578128/249373847-31ba5951-23e7-4566-88ad-39abe25eee0c.png)

Huh, i cant see it with my phone. Will check later thanks

**Comment by Rusenche** [comment]
> за reCAPTCHA ли говорите на тази страница? HektCaptcha може да го премине, използвате ли най-новата версия? Каква версия на hektCaptcha имате?

First I tested with the stable version: 0.2.8

Then I tested with: 0.3.0b2 - Faster 3x3 ReCaptcha solving

There was no positive result in both tests.

Practically nothing happens.

That's how it stands and nothing is automatically activated to automatically fill in the correct answers to those annoying squares.

![AJKJKAJ](https://github.com/Wikidepia/hektCaptcha-extension/assets/18578128/c2dc94f0-892c-402d-a225-35a1ac0427c5)

I am using Ungoogled Chromium v.114.0.5735.199 x64.

**Comment by Rusenche** [comment]
After more testing, I found that your extension doesn't work at all on Ungoogled Chromium. Although "hektCaptcha-v0.2.8.chrome" was added and then also tested with "hektCaptcha-v0.3.0b2".

I tested with another Chromium based browser. It turned out that "hektCaptcha-v0.2.8.chrome" - does not work on the site https://up-load.io/1bv6wr29l23y. But "hektCaptcha-v0.3.0b2" works after 5-6-7 correct markings of the correct squares, but the site rejects them with "please try again".

I believe you want to fix the extension.

Guys, test with Ungoogled Chromium for Windows: https://github.com/macchrome/winchrome/

All my tests concern the site https://up-load.io/1bv6wr29l23y where my observations are from, but I have proven to myself that the extension needs a new version with support for Ungoogled Chromium.

I'm done with the tests for today. My browser is Ungoogled
Chromium v.114.0.5735.199 x64 and I will watch you offer a new version that works on Ungoogled Chromium as well.

Guys, it's easier for your eventual tests to unzip your zip builds and load them unzipped in chrome://extensions/

:}

**Comment by Wikidepia** [comment]
> I tested with another Chromium based browser. It turned out that "hektCaptcha-v0.2.8.chrome" - does not work on the site https://up-load.io/1bv6wr29l23y. But "hektCaptcha-v0.3.0b2" works after 5-6-7 correct markings of the correct squares, but the site rejects them with "please try again".

Yeah, model to solve recaptcha is still bad, especially if you have low recaptcha score.

> All my tests concern the site https://up-load.io/1bv6wr29l23y where my observations are from, but I have proven to myself that the extension needs a new version with support for **Ungoogled Chromium** and **Bromite – buildtools** (https://github.com/uazo/bromite-buildtools/).
> 
> ![ssssss](https://user-images.githubusercontent.com/18578128/249503013-1ef0528e-79f5-4313-8d71-2680080c7b49.png)

Your browser doesn't seem to support web assembly, I dont know why but my ungoogled chromium works fine. wasm is needed for onnx which is essential to this extension. no wasm no hekt. sorry

**Comment by Rusenche** [comment]
> Your browser doesn't seem to support web assembly, I dont know why but my ungoogled chromium works fine. wasm is needed for onnx which is essential to this extension. no wasm no hekt.

What is your Ungoogled chromium? Can you link where you download it from?

I at least provided a link for Bromite - buildtools.

**Comment by Rusenche** [comment]
@Wikidepia

If you don't want to write - no problem. I came to this thread to help and point out facts.

**Comment by Wikidepia** [comment]
> @Wikidepia
> 
> If you don't want to write - no problem. I came to this thread to help and point out facts.

I download it from here https://ungoogled-software.github.io/ungoogled-chromium-binaries/

**Comment by Rusenche** [comment]
> > @Wikidepia
> > If you don't want to write - no problem. I came to this thread to help and point out facts.
> 
> I download it from here https://ungoogled-software.github.io/ungoogled-chromium-binaries/


I tested with https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/114.0.5735.199-1 on the site https://up-load.io/1bv6wr29l23y

Results:
**I**. When using **v.0.2.9** - `Fix solving hCaptcha bounding box` - by installing **crx**, then removing it and installing from https://chrome.google.com/webstore/detail/hektcaptcha-hcaptcha-solv/bpfdbfnkjelhloljelooneehdalcmljb/ and then - experimenting by loading unpack - `hektCaptcha-extension` _does not work in any way and this is when the extension is updated and uploaded 2 days ago_.

**II**. When using **v.0.3.0b2** - `Faster 3x3 ReCaptcha solving (hektCaptcha-v0.3.0b2.zip)` - by loading unpack (there is no other option to install). Voila - `hektCaptcha-extension` **works successfully**, even though this extension _was uploaded two weeks ago and is beta_.

I did these tests with the address you provided, which Ungoogle is great, I use its **Windows** version. This is all at its default settings, without installing any other extension, other than installing and experimenting with the different `hektCaptcha-extension` versions.

@Wikidepia, I don't know how **v.0.2.9** - `Fix solving hCaptcha bounding box` successfully worked for you, because it didn't work for me, even though there were no errors that I showed in a picture in my previous comments here.

**Comment by Wikidepia** [comment]
> **I**. When using **v.0.2.9** - `Fix solving hCaptcha bounding box` - by installing **crx**, then removing it and installing from https://chrome.google.com/webstore/detail/hektcaptcha-hcaptcha-solv/bpfdbfnkjelhloljelooneehdalcmljb/ and then - experimenting by loading unpack - `hektCaptcha-extension` _does not work in any way and this is when the extension is updated and uploaded 2 days ago_.

Can you try solving hCaptcha with v0.2.9? https://nopecha.com/demo/hcaptcha

**Comment by Rusenche** [comment]
As a regular user, I am not familiar with what `hCaptcha` is and/or what `reCaptcha` is.

But I did what you asked.
- installed from here https://chrome.google.com/webstore/detail/hektcaptcha-hcaptcha-solv/bpfdbfnkjelhloljelooneehdalcmljb/ **v.0.2.9**
- I opened the address you indicated: https://nopecha.com/demo/hcaptcha

Here is the result.
![v 0 2 9](https://github.com/Wikidepia/hektCaptcha-extension/assets/18578128/459b32dc-8feb-4f1a-a2a6-2ded28e4a79a)

As for this:
> If v.0.2.9 solved hcaptcha then there might be bug in recaptcha visibility check in v.0.3.x.

I have no idea, but I hope you will post an updated version (after v.0.2.9) that will successfully work from now on https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/114.0.5735.199-1. When you post a new version, I'll test again at https://up-load.io/1bv6wr29l23y

Greetings

**Comment by Rusenche** [comment]
@Wikidepia 

i tested https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.2.10 again at https://up-load.io/1bv6wr29l23y but the extension doesn't even start doing anything...

**Comment by Rusenche** [comment]
@Wikidepia

I tested the new version https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.2.11 again at https://up-load.io/1bv6wr29l23y but the extension doesn't even start doing anything...

/Ungoogled Chromium v.116.0.5845.97 x64/

**Comment by Rusenche** [comment]
@Wikidepia

I tested the new version https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.2.12 again at https://up-load.io/1bv6wr29l23y but the extension doesn't even start doing anything...

/Ungoogled Chromium v.116.0.5845.97 x64/

**Comment by Wikidepia** [comment]
reCaptcha only supported in beta version (v0.3.0b)
